[book]
authors = ["Tyler McCann (@tylerdotrar)"]
language = "en"
multilingual = false
src = "src"
title = "Rem Station Documentation Site"

[build]
build-dir = "public"

[output.html]
cname="docs.remstations.com"
